### PR TITLE
Serial Killer French translation

### PR DESCRIPTION
**Pull request by MisterClems**

### CODE REVIEW

**Comment by TimGoll** [comment]
Is there a reason why you deleted it?

**Comment by MisterClems** [comment]
I wasnt sure if i needed to translate role by role or direcly here https://github.com/TTT-2/ttt2-translation/blob/master/lua/autorun/example.lua
 so i closed the pull request for ask witch one @TimGoll

**Comment by TimGoll** [comment]
no, you did it right on your first try. Each addon has its own translation

**Comment by MisterClems** [comment]
Oh okey so i re open this one and i gonna translate all other role by role.

**Comment by TimGoll** [comment]
would be highly appreciated!

**Review by Histalek — APPROVED** [review]

**Comment by Alf21** [comment]
Yea role by role is a lot of fork-creating work, but it's the best way to keep add-ons independent and still up-to-date

**Review by Alf21 — APPROVED** [review]

**Pull request merged**
